all : tsp.java
	javac tsp.java

test :
	@java -ea tsp oregon-mileage.txt test-instance.txt
#	@java -ea tsp oregon-mileage.txt small-instance.txt
#	@java -ea tsp oregon-mileage.txt medium-instance.txt
#	@java -ea tsp oregon-mileage.txt large-instance.txt

clean :
	rm *.class
